spring:
  application:
    name: location-service
  datasource:
    url: jdbc:postgresql://localhost:5432/location_db
    username: postgres
    password: arpon007
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  sql:
    init:
      platform: postgres

server:
  port: 8081
